name: Google Code Jam 2022

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gcj2022:
    name: Google Code Jam 2022
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: npm install and test
      run: docker run -v $(pwd)/2022:/app -w /app/test node /bin/bash -c "npm install && npm test"
