name: Google Code Jam 2013

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gcj2013:
    name: Google Code Jam 2013
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: npm install and test
      run: docker run -v $(pwd)/2013:/app -w /app/test node /bin/bash -c "npm install && npm test"
